### PR TITLE
dart2 upgrades

### PR DESCRIPTION
**Pull request by devoncarew**
@pq

### CODE REVIEW

**Review by pq — APPROVED** [review]
LGTM!

would be good to get the config right so the appveyor build passes, but that's extra credit!

**Comment by devoncarew** [comment]
Yeah, I think I'm just waiting for appveyor to support a 2.0.0 sdk? Or, are we there already?

**Comment by pq** [comment]
I think they do... At least the linter builds are passing...

https://ci.appveyor.com/project/pq/linter/branch/master

**Comment by kevmoo** [comment]
@devoncarew - going to publish?

**Comment by devoncarew** [comment]
published!

**Pull request merged**
