### PR TITLE
If no version, use Version.none

### PR DESCRIPTION
**Pull request by sethladd**
Completely not tested!

### CODE REVIEW

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
lgtm; will merge when the bots finish

**Comment by devoncarew** [comment]
fix #17

**Comment by sethladd** [comment]
Cool, thanks!

**Comment by sethladd** [comment]
There are other cases where the code gets the version from the pubspec. We might want to use Version.none if no version detected in all the places.

**Pull request merged**
