### PR TITLE
Updated search for pub cache directory on windows to align with the d…

### PR DESCRIPTION
**Pull request by bsutton**
…art documenation on where it is located. Logic falls back to original version of the pub cache can't be found at the expected version. The dart doco says the location can vary on different windows version and I suspect that fact is the source of this problem.

### CODE REVIEW

**Comment by bsutton** [comment]
Any chance this PR can be merged and published.

Its causing issues for windows users.

**Comment by devoncarew** [comment]
Hey - thanks for the PR; happy to take a look.

> to align with the dart documenation on where it is located

Can you link to those docs here (or, the lookup logic from dart-lang/pub)? I'd like to confirm what we should be doing here, and / or  update the code to reference the docs. Thanks!

**Comment by bsutton** [comment]
https://dart.dev/tools/pub/environment-variables#:~:text=By%20default%2C%20this%20directory%20is,depending%20on%20the%20Windows%20version.)

**Comment by bsutton** [comment]
Experience in the real world is that it is often located at %APPDATA%.

I've had two users of the conduit (previously aqueduct) project encounter this problem.

**Comment by bsutton** [comment]
I think this may depend on the package installer they use.

**Comment by devoncarew** [comment]
It looks like pub first looks in `Platform.environment['APPDATA']`, and then falls back to `Platform.environment['LOCALAPPDATA']`; we should likely replicate the same behavior in this package: 

https://github.com/dart-lang/pub/blob/master/lib/src/system_cache.dart#L39

**Comment by bsutton** [comment]
I've altered the code to bring it inline with the pub command logic with some changes required by nnbd.

**Review by devoncarew — APPROVED** [review]
looks good to me; thanks for the contribution!

**Pull request merged**
